#ifndef ACCESS_FLAGS_H
#define ACCESS_FLAGS_H

// Access flags for the Java Virtual Machine
enum access_flags {
    ACC_PUBLIC = 1,             // Declared public; may be accessed from outside its package.
    ACC_PRIVATE = 2,            // Declared private; usable only within the defining class.
    ACC_PROTECTED = 4,          // Declared protected; may be accessed within subclasses.
    ACC_STATIC = 8,             // Declared static.
    ACC_FINAL = 16,             // Declared final; never directly assigned to after object construction.
    ACC_SYNCHRONIZED = 32,      // Declared synchronized; invocation is wrapped by a monitor use.
    ACC_BRIDGE = 64,            // A bridge method, generated by the compiler.
    ACC_VARARGS = 128,          // Declared with variable number of arguments.
    ACC_ABSTRACT = 1024,        // Declared abstract; no implementation is provided.
    ACC_STRICT = 2048,          // Declared strictfp; floating-point mode is FP-strict.
    ACC_SYNTHETIC = 4096,       // Declared synthetic; not present in the source code.
    ACC_ENUM = 16384,           // Declared as an element of an enum.
    ACC_VOLATILE = 64,          // Declared volatile; cannot be cached.
    ACC_TRANSIENT = 128         // Declared transient; not written or read by a persistent object manager.
};

#endif // ACCESS_FLAGS_H